name: Bug Report
description: Report a reproducible bug or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        Please provide a clear description of what the bug is.

  - type: input
    id: env
    attributes:
      label: Environment
      description: Example: dev / prod, browser version, Docker setup, etc.

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List all steps needed to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Observe the error

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what should happen.

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Describe what actually happens.

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Include console or backend logs if applicable.
