name: Feature Request
description: Suggest a new feature or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Describe the feature**
        Explain the purpose, scope, and expected outcome of this feature.

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature valuable or necessary?

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What conditions must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Condition 1
        - [ ] Condition 2
        - [ ] Condition 3

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Notes (optional)
      description: Include relevant API endpoints, models, or architecture notes if known.
